### ISSUE TITLE
Variance

### ISSUE THREAD

**Issue by bhargavvader** [dsquareindia/CMFS-Feature-Selection#4]
I've committed a few lines to the 20NG notebook for variance. Can someone have a look? @dsquareindia  Sorry for not putting in a pull request, I was working on master of this and forgot.

**Comment by devashishd12** [comment]
@bhargavvader could you please migrate the changes you made to a new branch and open it as a pull request? That would facilitate the review process. I'm undoing the changes on master.

**Comment by devashishd12** [comment]
Closing.
